# Site settings
title: devrunning
header-img: img/home-bg.jpg
email:
description: "DevRunning"
baseurl: "/blog"
url: "https://devrunning.github.io"
twitter_username:
github_username:
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
