# Site settings
title: DevHealth
first_title: Dev
second_title: Health
header-img: img/home-bg.jpg
email:
description: "Because Developers could be healthy"
baseurl: ""
url: "https://devhealth.github.io"
twitter_username:
github_username:
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
